import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aashish Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <h1 className="text-3xl p-3 font-bold bg-red-500 text-white "> Code Step by step</h1>
           </header>
        {children}
        <footer>
          <h1 className="text-center p-5 mt-10 rounded-2xl bg-black text-white"> © 2024 Aashish Gharti </h1>
        </footer>
      </body>
    </html>
  );
}
