import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google";
import { Open_Sans } from "next/font/google";
import { Noto_Sans_Javanese } from "next/font/google";
import { Cedarville_Cursive } from "next/font/google";
// import localFont from "next/font/local";
import Nav from "./component/Nav.js"

//to use in tailwind css we add variable property too

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});
const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});
const notoSansJavanese = Noto_Sans_Javanese({
  subsets: ["latin"],
 variable: "--font-noto-sans-javanese",
});
const cedarvilleCursive = Cedarville_Cursive({
  subsets: ["latin"],
  weight: "400",
});

//outside fonts => jayu layo  milena
// const noto = localFont({
//   src: "/fonts/NotoSansJP-Black.woff2",
//   variable: "--font-noto",
// });

// ******************************************************************************
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aashish Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  ${geistMono.variable}  ${notoSansJavanese.variable} `}
      >
        {/* <header>
          <h1 className="text-4xl p-3 font-500 font-noto-sans-javanese bg-red-500 text-white" > Code Step by step</h1>
           </header> */}
           <header>
            <Nav />
           </header>
        {children}
        {/* <footer>
          <h1 className="text-center p-5 mt-10 rounded-2xl bg-black text-white"> © 2024 Aashish Gharti </h1>
        </footer> */}
      </body>
    </html>
  );
}
